name: Build

on:
  push:
    branches: [ "main", "develop", "peters" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Jest tests
        working-directory: ./backend
        run: npm run test

      - name: Run app
        if: always()
        working-directory: ./backend
        run: | 
          npm run start & 
          while ! nc -z localhost 3000; do 
            sleep 1 
          done

      - name: Test
        if: always()
        working-directory: ./backend
        run: npx cypress run --headless

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Upload Cypress screenshots
          path: backend/cypress/screenshots
          overwrite: true

      - name: Analyze with SonarQube
        if: always()
        # You can pin the exact commit or the version.
        # uses: SonarSource/sonarqube-scan-action@v1.1.0
        uses: sonarsource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Generate a token on SonarQube, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
          SONAR_HOST_URL: http://hopper.fh-swf.de/sonarqube #${{ vars.SONAR_HOST_URL }}
        with:
          # Additional arguments for the sonarcloud scanner
          args:
            -Dsonar.verbose=true

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

