name: Build

on:
  push:
    branches: [ "main", "develop", "peters" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Run app
        working-directory: ./backend
        run: npm start

      - name: Test
        working-directory: ./backend
        run: npx cypress run --headless

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

